import './globals.css'
import {Inter} from 'next/font/google'
import Navbar from "@/app/components/navbar/Navbar";
import ClientOnly from "@/app/components/ClientOnly";
import RegisterModal from "@/app/components/modals/RegisterModal";
import LoginModal from "@/app/components/modals/LoginModal";
import ToasterProvider from "@/app/Providers/ToasterProvider";
import getCurrentUser from "@/app/actions/getCurrentUser";
import BackToTop from "@/app/components/BackToTop";
import Footer from "@/app/components/Footer";
import SupportModal from "@/app/components/modals/SupportModal";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'PC Store',
    description: 'Generated by create next app',
}

export default async function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    const currentUser = await getCurrentUser()

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="relative flex flex-col flex-auto">
                    <ClientOnly>
                        <ToasterProvider/>
                        <LoginModal/>
                        <RegisterModal/>
                        <SupportModal/>
                        <Navbar currentUser={currentUser}/>
                    </ClientOnly>
                    <div className="pb-20 flex-auto">
                        {children}
                    </div>
                    <BackToTop/>
                    <Footer/>
                </div>

            </body>
        </html>
    )
}
