import './globals.css'
import {Inter} from 'next/font/google'
import Navbar from "@/app/components/navbar/Navbar";
import ClientOnly from "@/app/components/ClientOnly";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'PC Store',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ClientOnly>
                    <Navbar/>

                </ClientOnly>
                <div className="pb-20 pt-28">
                    {children}
                </div>
            </body>
        </html>
    )
}
